import { prisma } from "@/lib/db";
import { usd, fmtDate } from "@/lib/format";
import { loadIntake } from "@/lib/intake";
import { buildBooksSummaries } from "@/lib/strategies/books";
import type { TraceStep } from "@/lib/strategies/analyzer";

export const dynamic = "force-dynamic";

// The printable CPA briefing document. Print with Ctrl/Cmd+P -> Save as PDF.
export default async function BriefingPage() {
  const [results, strategies, intake, books] = await Promise.all([
    prisma.strategyResult.findMany({ where: { relevant: true }, orderBy: { estimatedSavings: "desc" } }),
    prisma.strategy.findMany(),
    loadIntake(),
    buildBooksSummaries(),
  ]);
  const stratById = new Map(strategies.map((s) => [s.id, s]));
  const total = results.reduce((s, r) => s + r.estimatedSavings, 0);
  const groupIncome = books.reduce((s, b) => s + b.income12, 0);
  const groupNet = books.reduce((s, b) => s + b.net12, 0);

  return (
    <div>
      <div className="toolbar noprint">
        <a className="btn secondary" href="/plan">← Back to plan</a>
        <span className="small mut">Press Ctrl/Cmd+P and choose &quot;Save as PDF&quot; to export this briefing.</span>
      </div>

      <h1>CPA Briefing — Tax Strategy Review</h1>
      <p className="subtitle">
        Andersen group of companies · prepared {fmtDate(new Date())} · generated by Ledger + Strategist
      </p>

      <div className="card">
        <h3 style={{ marginTop: 0 }}>Purpose of this document</h3>
        <p className="small">
          The owner uses software to organize the group&apos;s books and screen for commonly applicable
          tax strategies. This briefing lists the candidates worth professional review, with the
          data and assumptions behind each estimate. <b>Nothing here is tax advice and nothing has
          been acted on.</b> We&apos;re asking you to confirm eligibility, correct the assumptions, and
          quantify properly where a strategy is worth pursuing.
        </p>
      </div>

      <h2>Group snapshot (trailing 12 months, cash basis, from books)</h2>
      <table className="data">
        <thead><tr><th>Entity</th><th>Role (per owner intake)</th><th>Tax treatment (per owner)</th><th className="num">Income</th><th className="num">Net</th></tr></thead>
        <tbody>
          {books.map((b) => {
            const ei = intake.entities[b.slug];
            return (
              <tr key={b.slug}>
                <td>{b.name}</td>
                <td className="small">{ei?.role.replace("_", " ")}{ei && !ei.confirmed ? " (UNCONFIRMED)" : ""}</td>
                <td className="small">{ei?.taxTreatment.replace("_", " ")}</td>
                <td className="num">{usd(b.income12)}</td>
                <td className={`num ${b.net12 >= 0 ? "" : "neg"}`}>{usd(b.net12)}</td>
              </tr>
            );
          })}
          <tr className="total"><td>Group</td><td /><td /><td className="num">{usd(groupIncome)}</td><td className="num">{usd(groupNet)}</td></tr>
        </tbody>
      </table>

      <h2>Candidate strategies ({results.length}) — estimated combined opportunity ~{usd(total)}/yr</h2>
      <p className="xsmall mut">
        Estimates use the owner&apos;s assumed {Math.round(intake.owner.fedMarginalRate * 100)}% federal
        marginal rate + Utah flat tax. Several figures are timing/deferral benefits, noted inline.
        All year-sensitive limits are flagged VERIFY.
      </p>

      {results.map((r, idx) => {
        const s = stratById.get(r.strategyId);
        const trace = JSON.parse(r.mathTraceJson) as TraceStep[];
        const checklist = JSON.parse(r.cpaChecklistJson) as string[];
        return (
          <div className="card" key={r.id}>
            <b>{idx + 1}. {s?.name}</b> — <span className="pos">{r.estimatedSavings > 0 ? `~${usd(r.estimatedSavings)}/yr estimated` : "no $ estimate (structural)"}</span>
            <p className="small" style={{ margin: "6px 0" }}>{r.summary}</p>
            <div className="xsmall mut">Provision: {s?.provision}</div>
            <table className="data" style={{ marginTop: 8 }}>
              <tbody>
                {trace.map((t, i) => (
                  <tr key={i}>
                    <td className="small">{t.label}{t.note && <span className="xsmall warn"> — {t.note}</span>}</td>
                    <td className="num small">{t.value === undefined ? "" : t.value < 1 && t.value > 0 ? `${(t.value * 100).toFixed(2)}%` : usd(t.value)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {checklist.length > 0 && (
              <>
                <div className="small" style={{ marginTop: 8 }}><b>Verification requested:</b></div>
                <ul className="small" style={{ marginTop: 4 }}>{checklist.map((c, i) => (<li key={i}>{c}</li>))}</ul>
              </>
            )}
          </div>
        );
      })}

      <p className="disclaimer">
        Estimate only. Verify eligibility and current law with your CPA before acting. This
        software does not file taxes or give final tax advice; figures are screening estimates
        derived from bookkeeping data and owner-provided answers.
      </p>
    </div>
  );
}
